# Generated by Django 2.2.5 on 2019-09-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(max_length=500, verbose_name='decription')),
                ('deadline', models.DateField(verbose_name='dead line')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='completed at')),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'todos',
                'ordering': ('completed_at', 'deadline'),
            },
        ),
    ]
